INSERT INTO products (id, name, slug, series, voltage, ah, cca, warranty, image, description, is_published, warranty_options, application) VALUES
(
    'prod-tz4lb', 
    'GW-TZ4LB', 
    'gw-tz4lb', 
    'Goodwin SMF', 
    '12V', 
    '4Ah', 
    'N/A', 
    '48 Months', 
    '/assets/products/Goodwin mockups/TZ4LB /TZ4LB__Green 48M.png', 
    'Reliable starting power designed for Indian riding conditions.', 
    true, 
    ARRAY['48 Months'], 
    ARRAY['Two Wheeler','Motorcycle']
  ),
(
    'prod-xl5lb', 
    'GW-XL5LB', 
    'gw-xl5lb', 
    'Goodwin SMF', 
    '12V', 
    '5Ah', 
    'N/A', 
    '48 Months', 
    '/assets/products/Goodwin mockups/XL5LB /XL5LB__BLACK GREEN 48M.png', 
    'High performance battery providing quick and consistent starts.', 
    true, 
    ARRAY['48 Months'], 
    ARRAY['Two Wheeler','Motorcycle']
  ),
(
    'prod-xl25lc', 
    'GW-XL2.5LC', 
    'gw-xl2-5lc', 
    'Goodwin SMF', 
    '12V', 
    '2.5Ah', 
    'N/A', 
    '48 Months', 
    '/assets/products/Goodwin mockups/xl2.5lc/XL2.5LC GREEN 48M.png', 
    'Compact and powerful battery optimized for kick-start and basic electricals.', 
    true, 
    ARRAY['48 Months'], 
    ARRAY['Two Wheeler','Motorcycle','Kick Start']
  ),
(
    'prod-tz5lb', 
    'GW-TZ5LB', 
    'gw-tz5lb', 
    'Goodwin SMF', 
    '12V', 
    '5Ah', 
    'N/A', 
    '48 Months', 
    '/assets/products/Goodwin mockups/TZ5LB /TZ5LB GREEN.png', 
    'Advanced power delivery for modern two wheelers with extra electronics.', 
    true, 
    ARRAY['48 Months'], 
    ARRAY['Two Wheeler','Motorcycle']
  ),
(
    'prod-12smf8', 
    'GW-12SMF8-UPS', 
    'gw-12smf8-ups', 
    'Goodwin Industrial', 
    '12V', 
    '8Ah', 
    'N/A', 
    '12 Months', 
    '/assets/products/Goodwin mockups/vrla 12v 8ah/vrla 12v 8ah png.png', 
    'Highly reliable VRLA battery for UPS and backup power applications.', 
    true, 
    ARRAY['12 Months'], 
    ARRAY['UPS & Inverters','Emergency Lighting','Security Systems']
  ),
(
    'prod-4smf5', 
    'GW-4SMF5', 
    'gw-4smf5', 
    'Goodwin Industrial', 
    '4V', 
    '5Ah', 
    'N/A', 
    '6 Months', 
    '/assets/products/Goodwin mockups/Vrla 4v5ah/Black Battery 04 FRONT.png', 
    'Compact SMF battery optimized for portable lighting and small electronics.', 
    true, 
    ARRAY['6 Months'], 
    ARRAY['Torch & Emergency Lights','Toys','Scales']
  ),
(
    'prod-4v7ah', 
    'GW-4V7AH-VRLA', 
    'gw-4v7ah-vrla', 
    'Goodwin Industrial', 
    '4V', 
    '7Ah', 
    'N/A', 
    '6 Months', 
    '/assets/products/Goodwin mockups/Vrla 4v7ah/Black Battery 01 FRONT.png', 
    'Reliable power for electronic weighing scales and emergency lamps.', 
    true, 
    ARRAY['6 Months'], 
    ARRAY['Scales & Emergency Lights','Medical Equipment']
  ),
(
    'prod-6v5ah', 
    'GW-6V5AH', 
    'gw-6v5ah', 
    'Goodwin Industrial', 
    '6V', 
    '5Ah', 
    'N/A', 
    '6 Months', 
    '/assets/products/Goodwin mockups/Vrla 6v5ah/Black Battery 03 FRONT.png', 
    'Deep discharge capable SMF battery for ride-on toys and medical equipment.', 
    true, 
    ARRAY['6 Months'], 
    ARRAY['Toys & Medical Devices']
  ),
(
    'prod-li-agro14', 
    'GW-LITHIUM-AGRO-14AH', 
    'gw-lithium-agro-14ah', 
    'Goodwin Lithium', 
    '12V', 
    '14Ah', 
    'N/A', 
    '12 Months', 
    '/assets/products/goodwin-lithium-agro-12v-14ah.png', 
    'Ultra lightweight, high life-cycle lithium battery designed for agricultural sprayers.', 
    true, 
    ARRAY['12 Months'], 
    ARRAY['Agricultural & Sprayers','Solar']
  ),
(
    'prod-li-ups8', 
    'GW-LITHIUM-UPS-8AH', 
    'gw-lithium-ups-8ah', 
    'Goodwin Lithium', 
    '12V', 
    '8Ah', 
    'N/A', 
    '12 Months', 
    '/assets/products/Goodwin mockups/LI-ion 12v8ah/Black Battery 05  LI.png', 
    'Premium lithium drop-in replacement for standard 12V 7Ah/8Ah lead acid UPS batteries.', 
    true, 
    ARRAY['12 Months'], 
    ARRAY['UPS & Inverters']
  ),
(
    'prod-vrla-agro14', 
    'GW-VRLA-AGRO-14AH', 
    'gw-vrla-agro-14ah', 
    'Goodwin Industrial', 
    '12V', 
    '14Ah', 
    'N/A', 
    '6 Months', 
    '/assets/products/Goodwin mockups/Vrla 12v14ah/Black Battery 02 FRONT.png', 
    'Heavy duty VRLA battery optimized for continuous cyclic use in agricultural sprayers.', 
    true, 
    ARRAY['6 Months'], 
    ARRAY['Agricultural & Sprayers']
  ),
(
    'prod-gold-14ah', 
    'GW-GOLD 14AH', 
    'gw-gold-14ah', 
    'Goodwin Gold', 
    '12V', 
    '14Ah', 
    'N/A', 
    '12 Months', 
    '/assets/products/Goodwin mockups/Gold Series 12v14ah/Gold Series.png', 
    'Premium Gold Series 12V 14Ah VRLA battery engineered for E-Bikes and Agricultural Sprayers.', 
    true, 
    ARRAY['12 Months'], 
    ARRAY['E-Bikes','Agricultural & Sprayers']
  ),
(
    'prod-inverter-tubular', 
    'GW-INVERTER TUBULAR', 
    'gw-inverter-tubular', 
    'Goodwin Home', 
    '12V', 
    '150Ah', 
    'N/A', 
    '72 Months', 
    '/assets/products/Goodwin mockups/Inverter Batteries/Inverter Batteries.png', 
    'High capacity tall tubular battery for uninterrupted power supply in homes and offices.', 
    true, 
    ARRAY['72 Months'], 
    ARRAY['Home Inverter','Solar','UPS']
  ),
(
    'prod-gold-series-6v-4-2ah', 
    'GOLD SERIES 6V 4.2AH', 
    'gold-series-6v-4-2ah', 
    'Goodwin Gold', 
    '6V', 
    '4.2Ah', 
    'N/A', 
    '12 Months', 
    '/assets/products/Goodwin mockups/gold series 6v 4.2ah/Gold series 2 1.png', 
    'Premium 6V 4.2Ah battery by Goodwin.', 
    true, 
    ARRAY['12 Months'], 
    ARRAY['General Purpose']
  ),
(
    'prod-gold-series-12v-12ah', 
    'GOLD SERIES 12V 12AH', 
    'gold-series-12v-12ah', 
    'Goodwin Gold', 
    '12V', 
    '12Ah', 
    'N/A', 
    '12 Months', 
    '/assets/products/Goodwin mockups/gold series 12v 12ah/Gold series 6 1.png', 
    'Premium 12V 12Ah battery by Goodwin.', 
    true, 
    ARRAY['12 Months'], 
    ARRAY['General Purpose']
  ),
(
    'prod-gold-series-12v-15ah', 
    'GOLD SERIES 12V 15AH', 
    'gold-series-12v-15ah', 
    'Goodwin Gold', 
    '12V', 
    '15Ah', 
    'N/A', 
    '12 Months', 
    '/assets/products/Goodwin mockups/gold series 12v 15ah/Gold series 7 1.png', 
    'Premium 12V 15Ah battery by Goodwin.', 
    true, 
    ARRAY['12 Months'], 
    ARRAY['General Purpose']
  ),
(
    'prod-gold-series-6v-4-5ah', 
    'GOLD SERIES 6V 4.5AH', 
    'gold-series-6v-4-5ah', 
    'Goodwin Gold', 
    '6V', 
    '4.5Ah', 
    'N/A', 
    '12 Months', 
    '/assets/products/Goodwin mockups/gold series 6v 4.5ah/Gold series 3.png', 
    'Premium 6V 4.5Ah battery by Goodwin.', 
    true, 
    ARRAY['12 Months'], 
    ARRAY['General Purpose']
  ),
(
    'prod-gold-series-12v-7-2ah', 
    'GOLD SERIES 12V 7.2AH', 
    'gold-series-12v-7-2ah', 
    'Goodwin Gold', 
    '12V', 
    '7.2Ah', 
    'N/A', 
    '12 Months', 
    '/assets/products/Goodwin mockups/gold series 12v 7.2ah/Gold series 4 1.png', 
    'Premium 12V 7.2Ah battery by Goodwin.', 
    true, 
    ARRAY['12 Months'], 
    ARRAY['General Purpose']
  ),
(
    'prod-gold-series-12v-9ah', 
    'GOLD SERIES 12V 9AH', 
    'gold-series-12v-9ah', 
    'Goodwin Gold', 
    '12V', 
    '9Ah', 
    'N/A', 
    '12 Months', 
    '/assets/products/Goodwin mockups/gold series 12v 9ah/Gold series 5 1.png', 
    'Premium 12V 9Ah battery by Goodwin.', 
    true, 
    ARRAY['12 Months'], 
    ARRAY['General Purpose']
  ),
(
    'prod-gold-series-12v-17ah', 
    'GOLD SERIES 12V 17AH', 
    'gold-series-12v-17ah', 
    'Goodwin Gold', 
    '12V', 
    '17Ah', 
    'N/A', 
    '12 Months', 
    '/assets/products/Goodwin mockups/gold series 12v 17ah/Gold series 8 1.png', 
    'Premium 12V 17Ah battery by Goodwin.', 
    true, 
    ARRAY['12 Months'], 
    ARRAY['General Purpose']
  )
ON CONFLICT (id) DO UPDATE SET 
  name = EXCLUDED.name,
  slug = EXCLUDED.slug,
  series = EXCLUDED.series,
  voltage = EXCLUDED.voltage,
  ah = EXCLUDED.ah,
  warranty = EXCLUDED.warranty,
  image = EXCLUDED.image,
  description = EXCLUDED.description,
  warranty_options = EXCLUDED.warranty_options,
  application = EXCLUDED.application;